version: '3.1'
services:
  tomcat:
    restart: always
    image: tomcat
    container_name: tomcat
    ports:
      - 8080:8080
    volumes:
      - ./dist/:/usr/local/tomcat/webapps/ROOT
    environment:
      TZ: Asia/Shanghai
